//
//  ContentLocal.swift
//  Cyberlingo
//
//  Created by Suren Kazaryan on 31.01.25.
//

import Foundation
import AVFoundation
import UIKit

struct Courses {
    
    static func giveCourseBuLanguage() -> [CourseViewModel] {
        //MARK: - ENGLISH -
        let language = Locale.current.language.languageCode?.identifier ?? ""
        switch language {
        case Language.en.rawValue:
            return coursesEn
        case Language.ru.rawValue:
            return courses
        default:
            return coursesEn
        }
        //MARK: - ENGLISH -
    }
    
    
    //MARK: COURSES
    static var courses: [CourseViewModel] =
    [CourseViewModel(
        id: 0,
        name: LocalisationManager.basicCourse,
        imageName: "EdLvl1",
        isBlocked: false, isExamPassed: false,
        color: ColorLib.realLowLil.rawValue,//UIColor().hexStringToUIColor(hex: "466CFF")
        description: LocalisationManager.basicCourseDescription,
        lessons: [
            LessonViewModel(id: 3,
                            lessonType: .password,
                            name: LocalisationManager.passwordCourse,
                            imageName: ImageLib.password.rawValue,
                            view1image: "passwordSec",
                            view1name: "Password security",
                            view1videoUrl: "SaAwW-6wV_Q",
                            view1description: "A dictionary attack is a password-cracking method where an attacker uses a precompiled list of common passwords or their variations. This list (dictionary) may include simple passwords like \"123456\" or \"password,\" as well as real words, names, birth dates, and frequently used character combinations. This method is faster than brute force since it only tests likely passwords, but it becomes ineffective if the user has chosen a strong and unique password.\n\nA brute force attack is a method where an attacker systematically tries all possible character combinations until the correct password is found. Unlike a dictionary attack, this approach does not rely on common passwords but instead tests every possible one, starting from the shortest. While brute force guarantees success, it requires significant computational power and time, especially for long passwords containing mixed characters (uppercase, lowercase, numbers, and symbols). Protection measures include using strong passwords, limiting login attempts, and enabling two-factor authentication.",
                            isBlocked: false, isExamPassed: false,
                            color: "466CFF",
                            description: "Learn password hashing, cracking methods, and protection strategies",
                            contentLesson: [ContentLessonViewModel(id: 0,
                                                  name: "Dictionary attack",
                                                  translate: "Хлеб",
                                                  transcription: "Enter different passwords to see how fast an attacker can crack them. All data is processed securely and stays on your device.",
                                                  image: "🍞",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "Enter different passwords to see how fast an attacker can crack them. All data is processed securely and stays on your device.", sound: "bread",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "Brute force attack",
                                                  translate: "Соль",
                                                  transcription: "Enter different passwords to see how fast an attacker can crack them.\nAll data is processed securely and stays on your device.",
                                                  image: "🧂",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "Enter different passwords to see how fast an attacker can crack them. All data is processed securely and stays on your device.", sound: "salt",
                                                  isFlipped: false),], quizQuestions: []),
            LessonViewModel(id: 0,
                            lessonType: .ceaserEncryption,
                            name: LocalisationManager.cryptographyCourse,
                            imageName: ImageLib.encrypting.rawValue,
                            view1image: "caesar",
                            view1name: "Caesar cipher",
                            view1videoUrl: "l6jqKRXSShI",
                            view1description: "The Caesar cipher is a simple encryption method where each letter in the plaintext is shifted by a fixed number of positions in the alphabet. For example, with a shift of 3, 'A' becomes 'D', 'B' becomes 'E', and so on. When the alphabet ends, the shift wraps around (e.g., 'Z' → 'C' in English).\n\nThis cipher is easy to break using brute force (since there are only 25 possible shifts in English) or frequency analysis. However, it serves as a fundamental concept in cryptography and is the basis for more advanced encryption techniques.",
                            isBlocked: false,
                            isExamPassed: false,
                            color: "466CFF",
                            description: "Learn encryption, hashing, digital signatures, and attacks",
                            contentLesson: [
                                ContentLessonViewModel(id: 0,
                                              name: "cyber",
                                              translate: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
                                              transcription: "abcdefghijklmnopqrstuvwxyz",
                                              image: "👋",
                                              type: "",
                                              category: "",
                                              remember: 0,
                                              module: "", description: "", sound: "hello",
                                              isFlipped: false),
                                ContentLessonViewModel(id: 0,
                                              name: "Hello world!",
                                              translate: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
                                              transcription: "abcdefghijklmnopqrstuvwxyz",
                                              image: "🍀",
                                              type: "",
                                              category: "",
                                              remember: 0, module: "", description: "", sound: "",
                                              isFlipped: false),
                                ContentLessonViewModel(id: 0,
                                              name: "Red blue team",
                                              translate: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
                                              transcription: "abcdefghijklmnopqrstuvwxyz",
                                              image: "🍀",
                                              type: "",
                                              category: "",
                                              remember: 0, module: "", description: "", sound: "",
                                              isFlipped: false),
                            ], quizQuestions: []),
            LessonViewModel(id: 1,
                            lessonType: .phishingSwipeQuiz,
                            name:LocalisationManager.phishingCourse,
                            imageName: ImageLib.phishing.rawValue,
                            view1image: "phishingLes",
                            view1name: "Email phishing",
                            view1videoUrl: "BnmneAjVrM4",
                            view1description: "Phishing is a type of cyber attack where scammers trick people into revealing sensitive information, such as passwords, credit card details, or personal data. They usually do this by sending fake emails, messages, or websites that look like legitimate ones from banks, social media, or other trusted organizations. These deceptive messages often create a sense of urgency, prompting victims to click on malicious links or download harmful attachments.\n\nTo protect against phishing, it's essential to stay cautious and verify the authenticity of any unexpected requests for personal information. Always check the sender's email address, avoid clicking on suspicious links, and enable two-factor authentication for extra security. Using security software and keeping it updated can also help prevent phishing attacks.",
                            isBlocked: false, isExamPassed: false,
                            color: "466CFF",
                            description: "Learn attack methods, detection, and prevention",
                            contentLesson: [ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "You must have spotted the look-alike URL. Be cautious about hyperlinks and attachments you open from emails — they may direct you to fraudulent websites where you're asked to input sensitive information.",
                                                  transcription: "You must have spotted the look-alike URL. Be cautious about hyperlinks and attachments you open from emails — they may direct you to fraudulent websites where you're asked to input sensitive information.",
                                                  image: "phishingEmail1",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "shirt",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "You must have spotted the mismatched domains and truly unbelievable offer.",
                                                  transcription: "",
                                                  image: "phishingEmail2",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "shirt",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "You must have noticed the scammers’ use of urgency to hide their use of the “note from seller” and other invoice fields.",
                                                  transcription: "",
                                                  image: "phishingEmail3",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "shirt",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "This is a legitimate Dropbox communication. The sender is “dropboxmail.com,” which is unusual but legitimate, and the URL is a secure link (https) to “dropbox.com.” If you are unsure about a domain, you can use a search engine to find out more information.",
                                                  transcription: "",
                                                  image: "phishingEmail4",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "shirt",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "This is almost identical to an attack used to successfully hack politicians’ emails. Always be sure to check URLs carefully!",
                                                  transcription: "",
                                                  image: "phishingEmail5",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "shirt",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "The hackers tried to use Google to hide the actual link, which is from tinyurl. An email similar to this was used to target think tanks and politicians.",
                                                  transcription: "",
                                                  image: "phishingEmail6",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "shirt",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "You must have spotted the clever look-alike URL and that the SMS came from an email address, not a phone number. If you ever have any doubts about a notification, don’t click the link; visit the site the way you normally do and get in touch with them that way.",
                                                  transcription: "",
                                                  image: "phishingEmail7",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "shirt",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "You must have spotted the suspicious offer and sneaky attempt to hide the real email.",
                                                  transcription: "",
                                                  image: "phishingEmail8",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "shirt",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "SMS scams are getting more common, but these links are all real.",
                                                  transcription: "",
                                                  image: "phishingEmail9",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "watch",
                                                  isFlipped: false),], quizQuestions: []),
            LessonViewModel(id: 4,
                            lessonType: .swipeQuizImage,
                            name: "AI or not (image)",
                            imageName: "image3d",
                            view1image: "aiOrNotDelse",
                            view1name: "AI generated pictures",
                            view1videoUrl: "ACWNZIkTTBM",
                            view1description: "AI generated pictures are visuals created by advanced AI systems using models such as GANs or diffusion techniques. These systems learn from vast image datasets to produce images that can be strikingly realistic and sometimes indistinguishable from real photos. However, this realism also poses a cybersecurity risk, as cybercriminals may exploit these images to create fake profiles, phishing emails, or fraudulent websites. Users can often detect generated images by checking for subtle inconsistencies in lighting, texture, or metadata that hint at a synthetic origin. Understanding AI's capabilities in producing realistic visuals is key to recognizing and avoiding potential scams, ensuring that content is critically evaluated before trust is established.",
                            isBlocked: false, isExamPassed: true,
                            color: "466CFF",
                            description: "Learn to identify AI-generated content using analysis techniques",
                            contentLesson: [ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotApple1",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotApple2",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotJapan1",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotJapan2",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotSea1",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotSea2",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotSun1",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotSun2",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotbalerin1",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotbalerin2",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),], quizQuestions: []),
            LessonViewModel(id: 4,
                            lessonType: .swipeQuizAudio,
                            name: "AI or not (voice)",
                            imageName: "voice3d",
                            view1image: "aiOrNotDelse",
                            view1name: "AI generated voice",
                            view1videoUrl: "ACWNZIkTTBM",
                            view1description: "AI generated pictures are visuals created by advanced AI systems using models such as GANs or diffusion techniques. These systems learn from vast image datasets to produce images that can be strikingly realistic and sometimes indistinguishable from real photos. However, this realism also poses a cybersecurity risk, as cybercriminals may exploit these images to create fake profiles, phishing emails, or fraudulent websites. Users can often detect generated images by checking for subtle inconsistencies in lighting, texture, or metadata that hint at a synthetic origin. Understanding AI's capabilities in producing realistic visuals is key to recognizing and avoiding potential scams, ensuring that content is critically evaluated before trust is established.",
                            isBlocked: false, isExamPassed: true,
                            color: "466CFF",
                            description: "Learn to identify AI-generated content using analysis techniques",
                            contentLesson: [ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "Asking for help woman",
                                                  image: " ",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "aiAudio1",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "Asking for help man",
                                                  image: " ",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "aiAudio2",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "Donald Trump",
                                                  image: " ",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "aiAudio3",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "Good man voice",
                                                  image: " ",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "aiAudio4",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "Ask for money man",
                                                  image: " ",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "aiAudio5",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "Good woman voice",
                                                  image: " ",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "aiAudio6",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "Apple",
                                                  transcription: "Donald Trump",
                                                  image: " ",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "naAudio1",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "Apple",
                                                  transcription: "Dogs atack",
                                                  image: " ",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "naAudio2",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "Apple",
                                                  transcription: "Woman voice",
                                                  image: " ",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "naAudio3",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "Apple",
                                                  transcription: "Asking for help man",
                                                  image: " ",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "naAudio4",
                                                  isFlipped: false),], quizQuestions: []),
            LessonViewModel(id: 4,
                            lessonType: .swipeQuizImage,
                            name: "AI or not",
                            imageName: ImageLib.artInt.rawValue,
                            view1image: "aiOrNotDelse",
                            view1name: "AI generated pictures",
                            view1videoUrl: "ACWNZIkTTBM",
                            view1description: "AI generated pictures are visuals created by advanced AI systems using models such as GANs or diffusion techniques. These systems learn from vast image datasets to produce images that can be strikingly realistic and sometimes indistinguishable from real photos. However, this realism also poses a cybersecurity risk, as cybercriminals may exploit these images to create fake profiles, phishing emails, or fraudulent websites. Users can often detect generated images by checking for subtle inconsistencies in lighting, texture, or metadata that hint at a synthetic origin. Understanding AI's capabilities in producing realistic visuals is key to recognizing and avoiding potential scams, ensuring that content is critically evaluated before trust is established.",
                            isBlocked: true, isExamPassed: false,
                            color: "466CFF",
                            description: "Learn to identify AI-generated content using analysis techniques",
                            contentLesson: [ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotApple1",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotApple2",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotJapan1",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotJapan2",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotSea1",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotSea2",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotSun1",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotSun2",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "true",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotbalerin1",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "false",
                                                  translate: "Apple",
                                                  transcription: "",
                                                  image: "aiOrNotbalerin2",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "", sound: "Apple",
                                                  isFlipped: false),], quizQuestions: []),
        ]),
     CourseViewModel(
        id: 1,
        name: LocalisationManager.IntermediateCourse,
        imageName: "EdLvl2",
        isBlocked: false,
        isExamPassed: false,
        color: ColorLib.realMidLil.rawValue,
        description: LocalisationManager.IntermediateDescription,
        lessons: [
            LessonViewModel(id: 2,
                            lessonType: .sqlInjection,
                            name: LocalisationManager.sqlInjectionCourse,
                            imageName: ImageLib.sqlIjection.rawValue,
                            view1image: "sqlInjection",
                            view1name: "SQL injection",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "SQL injection is an attack where a malicious user injects harmful SQL code into a database query through user input. For example, if a website processes login credentials with a query like SELECT * FROM users WHERE username = 'input' AND password = 'input', an attacker could enter ' OR '1'='1 as the password, bypassing authentication without a valid password.\n\nSuch attacks can allow an attacker to read, modify, or delete data, and in some cases, even take full control of the server. To prevent this, developers use prepared statements, input validation, and restrict database permissions.",
                            isBlocked: false, isExamPassed: false,
                            color: "466CFF",
                            description: "Learn to exploit and prevent SQL injections through hands-on testing",
                            contentLesson: [
                                ContentLessonViewModel(id: 0,
                                              name: "https://demo.testfire.net/login.jsp",
                                              translate: "SQL injection",
                                              transcription: "admin' --",
                                              image: "😀",
                                              type: "",
                                              category: "",
                                              remember: 0,
                                              module: "", description: "", sound: "head",
                                              isFlipped: false),
                                ContentLessonViewModel(id: 0,
                                              name: "https://www.list.am/login",
                                              translate: "https://www.list.am/login",
                                              transcription: "",
                                              image: "🫱",
                                              type: "",
                                              category: "",
                                              remember: 0,
                                              module: "", description: "", sound: "hand",
                                              isFlipped: false),], quizQuestions: []),
            LessonViewModel(id: 2,
                            lessonType: .sqlInjection,
                            name: "XSS",
                            imageName: "xssModule",
                            view1image: "sqlInjection",
                            view1name: "SQL injection",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "SQL injection is an attack where a malicious user injects harmful SQL code into a database query through user input. For example, if a website processes login credentials with a query like SELECT * FROM users WHERE username = 'input' AND password = 'input', an attacker could enter ' OR '1'='1 as the password, bypassing authentication without a valid password.\n\nSuch attacks can allow an attacker to read, modify, or delete data, and in some cases, even take full control of the server. To prevent this, developers use prepared statements, input validation, and restrict database permissions.",
                            isBlocked: true, isExamPassed: false,
                            color: "466CFF",
                            description: "Learn to exploit and prevent XSS atacks through hands-on testing",
                            contentLesson: [
                                ContentLessonViewModel(id: 0,
                                              name: "https://0aed001004dcb4a4801417a20033005d.web-security-academy.net/",
                                              translate: "XSS atack",
                                              transcription: "<script>alert(1)</script>",
                                              image: "😀",
                                              type: "",
                                              category: "",
                                              remember: 0,
                                              module: "", description: "", sound: "head",
                                              isFlipped: false),
                                ContentLessonViewModel(id: 0,
                                              name: "https://www.list.am/",
                                              translate: "https://www.list.am/",
                                              transcription: "<script>alert(1)</script>",
                                              image: "🫱",
                                              type: "",
                                              category: "",
                                              remember: 0,
                                              module: "", description: "", sound: "hand",
                                              isFlipped: false),], quizQuestions: []),
            LessonViewModel(id: 0,
                            lessonType: .symmetricEncryption,
                            name: "Symmetric encryption",
                            imageName: ImageLib.encrypting.rawValue,
                            view1image: "caesar",
                            view1name: "Caesar cipher",
                            view1videoUrl: "l6jqKRXSShI",
                            view1description: "The Caesar cipher is a simple encryption method where each letter in the plaintext is shifted by a fixed number of positions in the alphabet. For example, with a shift of 3, 'A' becomes 'D', 'B' becomes 'E', and so on. When the alphabet ends, the shift wraps around (e.g., 'Z' → 'C' in English).\n\nThis cipher is easy to break using brute force (since there are only 25 possible shifts in English) or frequency analysis. However, it serves as a fundamental concept in cryptography and is the basis for more advanced encryption techniques.",
                            isBlocked: true,
                            isExamPassed: false,
                            color: "466CFF",
                            description: "Learn encryption, hashing, digital signatures, and attacks",
                            contentLesson: [
                                ContentLessonViewModel(id: 0,
                                              name: "cyber",
                                              translate: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
                                              transcription: "abcdefghijklmnopqrstuvwxyz",
                                              image: "👋",
                                              type: "",
                                              category: "",
                                              remember: 0,
                                              module: "", description: "", sound: "hello",
                                              isFlipped: false),
                                ContentLessonViewModel(id: 0,
                                              name: "Hello world!",
                                              translate: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
                                              transcription: "abcdefghijklmnopqrstuvwxyz",
                                              image: "🍀",
                                              type: "",
                                              category: "",
                                              remember: 0, module: "", description: "", sound: "",
                                              isFlipped: false),
                                ContentLessonViewModel(id: 0,
                                              name: "Red blue team",
                                              translate: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
                                              transcription: "abcdefghijklmnopqrstuvwxyz",
                                              image: "🍀",
                                              type: "",
                                              category: "",
                                              remember: 0, module: "", description: "", sound: "",
                                              isFlipped: false),
                            ], quizQuestions: []),
        ]),
     CourseViewModel(id: 2,
                     name: LocalisationManager.AdvancedCourse,
                     imageName: "EdLvl3",
                     isBlocked: true,
                     isExamPassed: false,
                     color: ColorLib.realLil.rawValue,
                     description: LocalisationManager.AdvancedCourseDescription,
                     lessons: [])]
    
    
    //    //MARK: - ENGLISH -
    static var coursesEn: [CourseViewModel] = []
    
    
    static var coursesByTopic: [CourseTopicViewModel] =
    [CourseTopicViewModel(id: 0,
                          name: LocalisationManager.cryptographyCourse,
                          imageName: ImageLib.encrypting.rawValue,
                          isBlocked: false, isExamPassed: false,
                          color: ColorLib.realLowLil.rawValue,
                          description: LocalisationManager.cryptographyCourseDescription,
                          lessons: [LessonViewModel(id: 0,
                                                    lessonType: .coding,
                                                    name: "Small Talk",
                                                    imageName: "EducationSmallTalk",
                                                    view1image: "caesar",
                                                    view1name: "Ceaser",
                                                    view1videoUrl: "2OPVViV-GQk",
                                                    view1description: "asdasd",
                                                    isBlocked: false,
                                                    isExamPassed: false,
                                                    color: ColorLib.realLowLil.rawValue,
                                                    description: "",
                                                    contentLesson: [
                                                        ContentLessonViewModel(id: 0,
                                                                      name: "Բարև",
                                                                      translate: "Привет",
                                                                      transcription: "бар'ев",
                                                                      image: "👋",
                                                                      type: "",
                                                                      category: "",
                                                                      remember: 0,
                                                                      module: "", description: "", sound: "hello",
                                                                      isFlipped: false)], quizQuestions: [])]),
     CourseTopicViewModel(id: 1,
                          name:LocalisationManager.phishingCourse,
                          imageName: ImageLib.phishing.rawValue,
                          isBlocked: false, isExamPassed: false,
                          color: ColorLib.realLowLil.rawValue,
                          description: LocalisationManager.basicCourseDescription,
                          lessons: [LessonViewModel(id: 0,
                                                    lessonType: .coding,
                                                    name: "Small Talk",
                                                    imageName: "EducationSmallTalk",
                                                    view1image: "caesar",
                                                    view1name: "Ceaser",
                                                    view1videoUrl: "2OPVViV-GQk",
                                                    view1description: "asdasd",
                                                    isBlocked: false,
                                                    isExamPassed: false,
                                                    color: ColorLib.realLowLil.rawValue,
                                                    description: "",
                                                    contentLesson: [
                                                        ContentLessonViewModel(id: 0,
                                                                      name: "Բարև",
                                                                      translate: "Привет",
                                                                      transcription: "бар'ев",
                                                                      image: "👋",
                                                                      type: "",
                                                                      category: "",
                                                                      remember: 0,
                                                                      module: "", description: "", sound: "hello",
                                                                      isFlipped: false)], quizQuestions: [])]),
     CourseTopicViewModel(id: 2,
                          name: LocalisationManager.sqlInjectionCourse,
                          imageName: ImageLib.sqlIjection.rawValue,
                          isBlocked: false, isExamPassed: false,
                          color: ColorLib.realLowLil.rawValue,
                          description: LocalisationManager.basicCourseDescription,
                          lessons: [LessonViewModel(id: 0,
                                                    lessonType: .coding,
                                                    name: "Small Talk",
                                                    imageName: "EducationSmallTalk",
                                                    view1image: "caesar",
                                                    view1name: "Ceaser",
                                                    view1videoUrl: "2OPVViV-GQk",
                                                    view1description: "asdasd",
                                                    isBlocked: false,
                                                    isExamPassed: false,
                                                    color: ColorLib.realLowLil.rawValue,
                                                    description: "",
                                                    contentLesson: [
                                                        ContentLessonViewModel(id: 0,
                                                                      name: "Բարև",
                                                                      translate: "Привет",
                                                                      transcription: "бар'ев",
                                                                      image: "👋",
                                                                      type: "",
                                                                      category: "",
                                                                      remember: 0,
                                                                      module: "", description: "", sound: "hello",
                                                                      isFlipped: false)], quizQuestions: [])]),
     CourseTopicViewModel(id: 3,
                          name: LocalisationManager.passwordCourse,
                          imageName: ImageLib.password.rawValue,
                          isBlocked: false, isExamPassed: false,
                          color: ColorLib.realLowLil.rawValue,
                          description: LocalisationManager.basicCourseDescription,
                          lessons: [LessonViewModel(id: 0,
                                                    lessonType: .coding,
                                                    name: "Small Talk",
                                                    imageName: "EducationSmallTalk",
                                                    view1image: "caesar",
                                                    view1name: "Ceaser",
                                                    view1videoUrl: "2OPVViV-GQk",
                                                    view1description: "asdasd",
                                                    isBlocked: false,
                                                    isExamPassed: false,
                                                    color: ColorLib.realLowLil.rawValue,
                                                    description: "",
                                                    contentLesson: [
                                                        ContentLessonViewModel(id: 0,
                                                                      name: "Բարև",
                                                                      translate: "Привет",
                                                                      transcription: "бар'ев",
                                                                      image: "👋",
                                                                      type: "",
                                                                      category: "",
                                                                      remember: 0,
                                                                      module: "", description: "", sound: "hello",
                                                                      isFlipped: false)], quizQuestions: [])]),
     CourseTopicViewModel(id: 3,
                          name: "AI or not",
                          imageName: ImageLib.artInt.rawValue,
                          isBlocked: false, isExamPassed: false,
                          color: ColorLib.realLowLil.rawValue,
                          description: LocalisationManager.basicCourseDescription,
                          lessons: [LessonViewModel(id: 0,
                                                    lessonType: .coding,
                                                    name: "Small Talk",
                                                    imageName: "EducationSmallTalk",
                                                    view1image: "caesar",
                                                    view1name: "Ceaser",
                                                    view1videoUrl: "2OPVViV-GQk",
                                                    view1description: "asdasd",
                                                    isBlocked: false,
                                                    isExamPassed: false,
                                                    color: ColorLib.realLowLil.rawValue,
                                                    description: "",
                                                    contentLesson: [
                                                        ContentLessonViewModel(id: 0,
                                                                      name: "Բարև",
                                                                      translate: "Привет",
                                                                      transcription: "бар'ев",
                                                                      image: "👋",
                                                                      type: "",
                                                                      category: "",
                                                                      remember: 0,
                                                                      module: "", description: "", sound: "hello",
                                                                      isFlipped: false)], quizQuestions: [])]),
    ]
    
    static var certificates: [CourseViewModel] =
    [CourseViewModel(
        id: 0,
        name: LocalisationManager.basicCourse,
        imageName: "EdLvl1",
        isBlocked: false, isExamPassed: false,
        color: ColorLib.realLowLil.rawValue,
        description: LocalisationManager.basicCourseDescription,
        lessons: [
            LessonViewModel(id: 3,
                            lessonType: .quizQuestion,
                            name: "ISC2 CC ★☆☆☆☆",
                            imageName: ConstantNames.menu2,
                            view1image: "passwordSec",
                            view1name: "Password security",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "f",
                            isBlocked: false, isExamPassed: false,
                            color: "339F3E",
                            description: "International Information System Security Certification Consortium",
                            contentLesson: [ContentLessonViewModel(id: 0,
                                                  name: "Dictionary attack",
                                                  translate: "Хлеб",
                                                  transcription: "Enter different passwords to see how fast an attacker can crack them. All data is processed securely and stays on your device.",
                                                  image: "🍞",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "Enter different passwords to see how fast an attacker can crack them. All data is processed securely and stays on your device.", sound: "bread",
                                                  isFlipped: false),
                                    ContentLessonViewModel(id: 0,
                                                  name: "Brute force attack",
                                                  translate: "Соль",
                                                  transcription: "Enter different passwords to see how fast an attacker can crack them.\nAll data is processed securely and stays on your device.",
                                                  image: "🧂",
                                                  type: "",
                                                  category: "",
                                                  remember: 0,
                                                  module: "", description: "Enter different passwords to see how fast an attacker can crack them. All data is processed securely and stays on your device.", sound: "salt",
                                                  isFlipped: false)], quizQuestions: []),
            LessonViewModel(id: 3,
                            lessonType: .password,
                            name: "CISM ★★☆☆☆",
                            imageName: ConstantNames.menu2,
                            view1image: "passwordSec",
                            view1name: "Password security",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "f",
                            isBlocked: true, isExamPassed: false,
                            color: "339F3E",
                            description: "Certified Information Security Manager",
                            contentLesson: [], quizQuestions: []),
            LessonViewModel(id: 3,
                            lessonType: .password,
                            name: "SSCP ★★☆☆☆",
                            imageName: ConstantNames.menu2,
                            view1image: "passwordSec",
                            view1name: "Password security",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "f",
                            isBlocked: true, isExamPassed: false,
                            color: "339F3E",
                            description: "Systems Security Certified Practitioner",
                            contentLesson: [], quizQuestions: []),
            LessonViewModel(id: 3,
                            lessonType: .password,
                            name: "GSEC ★★★☆☆",
                            imageName: ConstantNames.menu2,
                            view1image: "passwordSec",
                            view1name: "Password security",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "f",
                            isBlocked: true, isExamPassed: false,
                            color: "339F3E",
                            description: "GIAC Security Essentials",
                            contentLesson: [], quizQuestions: []),
            LessonViewModel(id: 3,
                            lessonType: .password,
                            name: "CISSP ★★★☆☆",
                            imageName: ConstantNames.menu2,
                            view1image: "passwordSec",
                            view1name: "Password security",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "f",
                            isBlocked: true, isExamPassed: false,
                            color: "339F3E",
                            description: "Certified Information Systems Security Professional",
                            contentLesson: [], quizQuestions: []),
            LessonViewModel(id: 3,
                            lessonType: .password,
                            name: "OSCP ★★★★☆",
                            imageName: ConstantNames.menu2,
                            view1image: "passwordSec",
                            view1name: "Password security",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "f",
                            isBlocked: true, isExamPassed: false,
                            color: "339F3E",
                            description: "Offensive Security Certified Professional",
                            contentLesson: [], quizQuestions: []),
            LessonViewModel(id: 3,
                            lessonType: .password,
                            name: "GCIH ★★★★☆",
                            imageName: ConstantNames.menu2,
                            view1image: "passwordSec",
                            view1name: "Password security",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "f",
                            isBlocked: true, isExamPassed: false,
                            color: "339F3E",
                            description: "GIAC Certified Incident Handler",
                            contentLesson: [], quizQuestions: []),
            LessonViewModel(id: 3,
                            lessonType: .password,
                            name: "OSWE ★★★★☆",
                            imageName: ConstantNames.menu2,
                            view1image: "passwordSec",
                            view1name: "Password security",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "f",
                            isBlocked: true, isExamPassed: false,
                            color: "339F3E",
                            description: "Offensive Security Web Expert",
                            contentLesson: [], quizQuestions: []),
            LessonViewModel(id: 3,
                            lessonType: .password,
                            name: "CRTP ★★★★☆",
                            imageName: ConstantNames.menu2,
                            view1image: "passwordSec",
                            view1name: "Password security",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "f",
                            isBlocked: true, isExamPassed: false,
                            color: "339F3E",
                            description: "Certified Red Team Professional",
                            contentLesson: [], quizQuestions: []),
            LessonViewModel(id: 3,
                            lessonType: .password,
                            name: "CCSP ★★★★★",
                            imageName: ConstantNames.menu2,
                            view1image: "passwordSec",
                            view1name: "Password security",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "f",
                            isBlocked: true, isExamPassed: false,
                            color: "339F3E",
                            description: "Certified Cloud Security Professional",
                            contentLesson: [], quizQuestions: []),
            LessonViewModel(id: 3,
                            lessonType: .password,
                            name: "CISA ★★★★★",
                            imageName: ConstantNames.menu2,
                            view1image: "passwordSec",
                            view1name: "Password security",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "f",
                            isBlocked: true, isExamPassed: false,
                            color: "339F3E",
                            description: "Certified Information Systems Auditor",
                            contentLesson: [], quizQuestions: []),
            LessonViewModel(id: 3,
                            lessonType: .password,
                            name: "CHFI ★★★★★",
                            imageName: ConstantNames.menu2,
                            view1image: "passwordSec",
                            view1name: "Password security",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "f",
                            isBlocked: true, isExamPassed: false,
                            color: "339F3E",
                            description: "Computer Hacking Forensic Investigator",
                            contentLesson: [], quizQuestions: []),
            LessonViewModel(id: 3,
                            lessonType: .password,
                            name: "CPTC ★★★★★",
                            imageName: ConstantNames.menu2,
                            view1image: "passwordSec",
                            view1name: "Password security",
                            view1videoUrl: "2OPVViV-GQk",
                            view1description: "f",
                            isBlocked: true, isExamPassed: false,
                            color: "339F3E",
                            description: "Certified Penetration Testing Consultant",
                            contentLesson: [], quizQuestions: []),
        ])]
    
    
}

